
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product
    username: rabin
    password: rabin
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  main:
    allow-circular-references: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    depends-on: entityManagerFactory # flyway add

    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8050
